name: Package python packages

on:
  - workflow_call

jobs:
  build-packages:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [Ubuntu-20.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Collect OS specific build directory
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          name: speakeasy2-${{ runner.os }}-${{ matrix.python-version }}-${{  github.sha }}

      - name: Extract files
        run: |
          mv artifacts/ build/
          cp build/_speakeasy2.* speakeasy2

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up poetry
        uses: abatilo/actions-poetry@v2

      - name: Build package
        run: |
          poetry build

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
            name: speakeasy2-python-${{ runner.os }}-${{ matrix.python-version }}-${{ github.sha }}
            path: dist/*
